import * as THREE from 'three';
import { buildOffice } from '../src/js/world/office.js';
import { Lighting } from '../src/js/render/renderer.js';
import { QUALITY } from '../src/js/config.js';
import { Character, createSharedMaterials } from '../src/js/characters/character.js';
import { LOOKS } from '../src/js/characters/looks.js';
const P = new URLSearchParams(location.search);
const qn = P.get('q') || 'medium';
const r = new THREE.WebGLRenderer({ antialias: true });
r.shadowMap.enabled = true;
r.setSize(innerWidth, innerHeight); document.body.appendChild(r.domElement);
const scene = new THREE.Scene();
const world = buildOffice({ quality: QUALITY[qn] });
scene.add(world.root);
const light = new Lighting(scene, qn);
const t = parseFloat(P.get('t') || '560');
const shared = createSharedMaterials();
const pl = new Character(LOOKS.player, shared); pl.group.position.set(-2.2, 0, 1.2); pl.setYaw(Math.PI); scene.add(pl.group);
const an = new Character(LOOKS.anu, shared); an.group.position.set(-2.84, 0, -2.35); an.setYaw(0); an.anim.setBase('type'); an.anim.w={type:1}; scene.add(an.group);
const ra = new Character(LOOKS.rahul, shared); ra.group.position.set(-4.36, 0, -0.05); ra.setYaw(Math.PI); ra.anim.setBase('type'); ra.anim.w={type:1}; scene.add(ra.group);
const mg = new Character(LOOKS.manager, shared); mg.group.position.set(-1.2, 0, 1.4); mg.setYaw(-Math.PI/2); mg.anim.setBase('talk'); mg.anim.w={talk:1}; scene.add(mg.group);
for (let i = 0; i < 30; i++) [pl, an, ra, mg].forEach((c) => c.update(1 / 30));
light.update(t, new THREE.Vector3(-2, 0, 0), world.windowMat, 0.016);
world.update(0.016, t);
const cam = new THREE.PerspectiveCamera(60, innerWidth / innerHeight, 0.1, 100);
const view = (P.get('view') || '-2.2,2.6,4.6,-2.6,1.2,-3').split(',').map(Number);
cam.position.set(view[0], view[1], view[2]); cam.lookAt(view[3], view[4], view[5]);
r.render(scene, cam);
window.__info = r.info.render;
console.log('calls', r.info.render.calls, 'tris', r.info.render.triangles);
